USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS RAY_DB;
USE DATABASE RAY_DB;
CREATE SCHEMA IF NOT EXISTS RAY_SCHEMA;
USE SCHEMA RAY_SCHEMA;
CREATE WAREHOUSE IF NOT EXISTS RAY_WH;

USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE ROLE RAY_ROLE;
GRANT ROLE RAY_ROLE to ROLE SYSADMIN;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE RAY_ROLE;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE RAY_ROLE;
GRANT USAGE ON DATABASE RAY_DB TO ROLE RAY_ROLE;
GRANT USAGE ON SCHEMA RAY_DB.RAY_SCHEMA TO ROLE RAY_ROLE;
GRANT CREATE TABLE ON SCHEMA RAY_DB.RAY_SCHEMA TO ROLE RAY_ROLE;
GRANT SELECT, INSERT, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA RAY_DB.RAY_SCHEMA TO ROLE RAY_ROLE;
GRANT SELECT, INSERT, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA RAY_DB.RAY_SCHEMA TO ROLE RAY_ROLE;
GRANT CREATE STAGE ON SCHEMA RAY_DB.RAY_SCHEMA TO ROLE RAY_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA RAY_DB.RAY_SCHEMA TO ROLE RAY_ROLE;
GRANT CREATE FUNCTION on SCHEMA RAY_DB.RAY_SCHEMA TO ROLE RAY_ROLE;

GRANT CREATE IMAGE REPOSITORY ON SCHEMA RAY_DB.RAY_SCHEMA TO ROLE RAY_ROLE;
GRANT CREATE SERVICE ON SCHEMA RAY_DB.RAY_SCHEMA TO ROLE RAY_ROLE;
CREATE SECURITY INTEGRATION IF NOT EXISTS snowservices_ingress_oauth
  TYPE=oauth
  OAUTH_CLIENT=snowservices_ingress
  ENABLED=true;

CREATE NETWORK RULE IF NOT EXISTS ALLOW_ALL_RULE
  TYPE = 'HOST_PORT'
  MODE = 'EGRESS'
  VALUE_LIST= ('0.0.0.0:443', '0.0.0.0:80');
CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS ALLOW_ALL_EAI
  ALLOWED_NETWORK_RULES = (ALLOW_ALL_RULE)
  ENABLED = true;
GRANT USAGE ON INTEGRATION ALLOW_ALL_EAI TO ROLE RAY_ROLE;
GRANT USAGE ON WAREHOUSE RAY_WH to role RAY_ROLE;

// the steps to create snowflake_egress_access, snowflake_egress_access_integration and granting usage on snowflake_egress_access_integration are optional. They are only needed if we need to connect to data in Snowflake tables from within SPCS service.
CREATE OR REPLACE NETWORK RULE snowflake_egress_access
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('<YOUR_SNOWFLAKE_ACCOUNT>.snowflakecomputing.com');

CREATE EXTERNAL ACCESS INTEGRATION IF NOT Exists snowflake_egress_access_integration
  ALLOWED_NETWORK_RULES = (snowflake_egress_access)
  ENABLED = true;

GRANT USAGE ON INTEGRATION snowflake_egress_access_integration TO ROLE RAY_ROLE;

// this step is required
GRANT ROLE RAY_ROLE TO USER <YOUR_SNOWFLAKE_USER>;