FROM "sfsenorthamerica-demo391.registry.snowflakecomputing.com/container_hol_db/public/spcs_ray_image_repo/ray_base:eda7d5206c69f904b6c8abbc854a5522b38a42cd"
ENV PYTHONUNBUFFERED=1
ENTRYPOINT ["./entrypoint.sh", "rayhead"]