# Note that base image tag should not be 'latest' as it might cause false positive image cache hit.
FROM ${base_image} as build
RUN apt-get update -y
RUN apt-get install -y unzip git net-tools
COPY ${ray_requirements_file} ./${ray_requirements_file}
RUN pip3 install --upgrade pip
RUN pip3 install -r ${ray_requirements_file}
COPY  ${entrypoint_script} ./ ${entrypoint_script}
RUN chmod +x  ${entrypoint_script}
ENTRYPOINT ["./${entrypoint_script}"]